
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASIGNleftORleftANDleftEQNEQleftIMDMleftMASMENOSleftMULTDIVISIONAND ASIGN CONSTANT DIVISION DM EQ IDENTIFIER IM KEYWORDS LITERAL MAS MENOS MULT NEQ OR PUNCTUATIONprograma : KEYWORDS IDENTIFIER PUNCTUATION PUNCTUATION bloquebloque : PUNCTUATION declaraciones PUNCTUATIONdeclaraciones : declaraciones declaracion\n| declaraciondeclaracion : KEYWORDS IDENTIFIER PUNCTUATIONdeclaracion : IDENTIFIER ASIGN expresion PUNCTUATIONexpresion : expresion MAS expresion\n| expresion MENOS expresion\n| expresion MULT expresion\n| expresion DIVISION expresionexpresion : CONSTANT\n| IDENTIFIER'
    
_lr_action_items = {'KEYWORDS':([0,6,8,9,13,16,20,],[2,10,10,-4,-3,-5,-6,]),'$end':([1,7,12,],[0,-1,-2,]),'IDENTIFIER':([2,6,8,9,10,13,15,16,20,21,22,23,24,],[3,11,11,-4,14,-3,17,-5,-6,17,17,17,17,]),'PUNCTUATION':([3,4,5,8,9,13,14,16,17,18,19,20,25,26,27,28,],[4,5,6,12,-4,-3,16,-5,-12,20,-11,-6,-7,-8,-9,-10,]),'ASIGN':([11,],[15,]),'CONSTANT':([15,21,22,23,24,],[19,19,19,19,19,]),'MAS':([17,18,19,25,26,27,28,],[-12,21,-11,-7,-8,-9,-10,]),'MENOS':([17,18,19,25,26,27,28,],[-12,22,-11,-7,-8,-9,-10,]),'MULT':([17,18,19,25,26,27,28,],[-12,23,-11,23,23,-9,-10,]),'DIVISION':([17,18,19,25,26,27,28,],[-12,24,-11,24,24,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'bloque':([5,],[7,]),'declaraciones':([6,],[8,]),'declaracion':([6,8,],[9,13,]),'expresion':([15,21,22,23,24,],[18,25,26,27,28,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> KEYWORDS IDENTIFIER PUNCTUATION PUNCTUATION bloque','programa',5,'p_programa','PARSER_C.py',16),
  ('bloque -> PUNCTUATION declaraciones PUNCTUATION','bloque',3,'p_bloque','PARSER_C.py',20),
  ('declaraciones -> declaraciones declaracion','declaraciones',2,'p_declaraciones','PARSER_C.py',24),
  ('declaraciones -> declaracion','declaraciones',1,'p_declaraciones','PARSER_C.py',25),
  ('declaracion -> KEYWORDS IDENTIFIER PUNCTUATION','declaracion',3,'p_declaracion_variable','PARSER_C.py',32),
  ('declaracion -> IDENTIFIER ASIGN expresion PUNCTUATION','declaracion',4,'p_declaracion_asignacion','PARSER_C.py',36),
  ('expresion -> expresion MAS expresion','expresion',3,'p_expresion_binaria','PARSER_C.py',40),
  ('expresion -> expresion MENOS expresion','expresion',3,'p_expresion_binaria','PARSER_C.py',41),
  ('expresion -> expresion MULT expresion','expresion',3,'p_expresion_binaria','PARSER_C.py',42),
  ('expresion -> expresion DIVISION expresion','expresion',3,'p_expresion_binaria','PARSER_C.py',43),
  ('expresion -> CONSTANT','expresion',1,'p_expresion_valor','PARSER_C.py',47),
  ('expresion -> IDENTIFIER','expresion',1,'p_expresion_valor','PARSER_C.py',48),
]
